import Footer from "@/components/Footer";
import ActiveSectionContextProvider from "@/context/activeSectionContext";
import logo from "@/public/logo.png";
import { Inter } from "next/font/google";
import Image from "next/image";
import Header from "../components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className=" bg-[#FDF7F5]">
      <body className={` relative ${inter.className} `}>
        <div className="fixed hidden top-10 left-10 sm:block">
          <Image
            src={logo}
            alt="Logo du studio du Chrissy Ottenhof"
            width="50"
            height="100"
            quality="95"
            priority={true}
            className="bg-[#FDF7F5]"
          />
        </div>
        <ActiveSectionContextProvider>
          <main className="flex flex-col items-center min-h-screen mt-28 ">
            <Header />
            {children}
            <Footer />
          </main>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}

// bg-[#1c00fe] blue
// bg-[#89a1ff] light blue
// bg-[#ffcf00] yellow
// bg-[#ffeea0] light yellow
// bg-[#FDF7F5] light bronze
